# Generated by Django 4.0 on 2022-02-28 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=8)),
                ('Town', models.CharField(max_length=10)),
                ('Addr', models.CharField(max_length=50)),
                ('Body', models.CharField(max_length=500)),
                ('IsEnable', models.BooleanField(default=True)),
                ('IsPay', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyDate', models.DateTimeField(blank=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Advertisement',
            },
        ),
    ]
