# Generated by Django 4.0 on 2022-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='Image1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Image2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='IsEnable',
            field=models.BooleanField(default=False),
        ),
    ]
