# Generated by Django 4.0 on 2022-03-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_advertisement_image1_advertisement_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IPAddr', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'RateHistory',
            },
        ),
    ]
