# Generated by Django 4.0 on 2022-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_ratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratehistory',
            name='Val',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='CreateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ratehistory',
            name='CreateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
