# Generated by Django 4.0 on 2022-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0004_ratehistory_val_alter_advertisement_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='Image2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
