# Generated by Django 4.0 on 2022-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0005_alter_advertisement_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='IP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
